spring:
  datasource:
    url: jdbc:mysql://192.168.0.116:3306/talci_dev
    username: talci_dev_user
    password: talci
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: talci_database_create.sql